# Generated by Django 4.2.13 on 2024-06-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.AutoField(db_column='codCargo', primary_key=True, serialize=False)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('nombreCargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('categorias', models.CharField(choices=[('Vip', 'Vip'), ('Normal', 'Normal'), ('Economico', 'Economico'), ('Familiar', 'Familiar'), ('Suite', 'Suite'), ('Presidencial', 'Presidencial')], default='Normal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=10)),
                ('sueldo', models.IntegerField()),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('codCargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_FPago', models.AutoField(db_column='id_FPago', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(db_column='id_genero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='genero', max_length=20)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.IntegerField()),
                ('cant_banos', models.IntegerField()),
                ('cant_camas', models.IntegerField()),
                ('tamano_camas', models.CharField(max_length=50)),
                ('cant_personas_disp', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('estado_habitacion', models.CharField(max_length=50)),
                ('servicios_adicionales', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('patente_hotel', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('estado_habitacion', models.BooleanField()),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipos_habitaciones', models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Matrimonial', 'Matrimonial')], default='Simple', max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.habitacion')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.hotel')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.region')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apPaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('apMaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField(blank=True, db_column='fecha_nacimiento', null=True)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(max_length=15)),
                ('comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.comuna')),
                ('genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.genero')),
            ],
        ),
        migrations.CreateModel(
            name='HotelDetalle',
            fields=[
                ('id_hotel_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=350)),
                ('cantidad_habitaciones', models.IntegerField()),
                ('cantidad_empleados', models.IntegerField()),
                ('categoria_hotel', models.CharField(max_length=50)),
                ('servicios_adicionales', models.CharField(max_length=50)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.hotel')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.servicioadicional')),
                ('id_tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.tipohabitacion')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.hotel'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('fModificacion', models.DateTimeField(auto_now=True)),
                ('id_FPago', models.ForeignKey(db_column='id_FPago', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.formapago')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.empleado')),
                ('id_hotel', models.ForeignKey(db_column='id_hotel', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.hotel')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='hotelVeranum.persona'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelVeranum.provincia'),
        ),
    ]
