# Generated by Django 5.0.6 on 2024-06-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelVeranum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cantPersonas',
            new_name='precioReserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='idHotel',
        ),
    ]
